backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "content"
    label: "Content"
    folder: "_data/content"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
      - label: "Meta Tags"
        name: "meta"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}

  - name: "contact"
    label: "Contact"
    folder: "_data/contact"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
      - label: "Form Fields"
        name: "form"
        widget: "list"
        fields:
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["text","textarea"]}
          - {label: "Required", name: "required", widget: "boolean", default: true}
      - label: "Meta Tags"
        name: "meta"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}

  - name: "home"
    label: "Home"
    folder: "_data/home"
    extension: "json"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Background", name: "background", widget: "image"}
      - label: "Slideshow"
        name: "slideshow"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "Promos"
        name: "promos"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Text", name: "text", widget: "markdown"}
      - label: "Meta Tags"
        name: "meta"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}

  - label: "Settings"
    name: "settings"
    delete: false
    editor:
      preview: false
    files:
      - label: "Site Settings"
        name: "site-settings"
        file: "settings.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Keywords", name: "keywords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Share Image", name: "ogImage", widget: "string"}
          - label: "Menu"
            name: "menu"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
