backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "content"
    label: "Content"
    folder: "_data/content"
    extension: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

    editor:
      preview: false

  - label: "Settings"
    name: "settings"
    files:
      - label: "Settings"
        name: "settings"
        file: "settings.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Keywords", name: "keywords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Share Image", name: "ogImage", widget: "string"}
          - label: "Menu"
            name: "menu"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
