backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "content"
    label: "Content"
    folder: "_data/content"
    extension: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

    editor:
      preview: false
